### ISSUE TITLE
Make .npmignore file

### ISSUE THREAD

**Issue by f-xyz** [hwndept/node-seed#28]
Make NPM ignore tests and service stuff.

**Comment by hwndept** [comment]
Hey, @f-xyz, I am not familiar with .npmignore yet. I will take a look a bit later. Could you please explain what should be ignored and why?

**Comment by f-xyz** [comment]
Use a .npmignore file to keep stuff out of your package. If there's no .npmignore file, but there is a .gitignore file, then npm will ignore the stuff matched by the .gitignore file. If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it.

https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package
http://stackoverflow.com/questions/24942161/does-npm-ignore-files-listed-in-gitignore
http://stackoverflow.com/questions/25124844/should-i-npmignore-my-tests

**Comment by hwndept** [comment]
Thanks for the explanation. I have read about this feature and seems like for now it's not required to implement, because .gitignore is enough. Since this project will be used as a starter nodejs project, all files that are presented now are required.

@f-xyz Do you agree?

**Comment by f-xyz** [comment]
yep :100:

**Comment by hwndept** [comment]
Ok, thank you. I am going to close this issue.
