### ISSUE TITLE
Add .codeclimate.yml

### ISSUE THREAD

**Issue by Fleischers** [hwndept/node-seed#46]
Based on https://docs.codeclimate.com/docs/switching-to-code-climate-platform,
Project should have configuration file for Code Climate to utilize the benefits of platform with properly set engines for the project.

Engines suggested:
- [x] https://docs.codeclimate.com/docs/fixme
- [x] https://docs.codeclimate.com/docs/eslint
- [x] https://docs.codeclimate.com/docs/markdownlint
- [x] https://docs.codeclimate.com/docs/duplication
- [x] https://docs.codeclimate.com/docs/nodesecurity (will work only with `shrinkwrap.json`)
## Depends on
#48

**Comment by Fleischers** [comment]
It depends on #48 as to enable proper work of eslint engine the project should have `.eslintrc`, which lacks commit https://github.com/Fleischers/node-seed/commit/3bdb67ef0a72779776b4c354b1b9bba49217688b

**Comment by hwndept** [comment]
Will be good to include that configuration file. I have started already working on migration to eslint, will prepare a PR soon. After you can do a PR to the feature.

**Comment by hwndept** [comment]
shrink-wrap was added in #54

**Comment by hwndept** [comment]
oh, after I added shrink-wrap dependencies gathering took via `npm install` too much time, so I am not sure that it's good option.

**Comment by hwndept** [comment]
seems like I have found npm 3.x.x bug, after I have locked dependencies via `npm shrinkwrap` shirnkwrap.json contained dependencies that were not in a project(from another npm registry). I think npm got some packages form cache.
