### ISSUE TITLE
Any plans to switch to eslint instead of jshint?

### ISSUE THREAD

**Issue by Fleischers** [hwndept/node-seed#47]
One of the reasons can be ability to set configurations for Code Climate which uses Eslint as its main engine for Javascript and can reuse configuration from project during its code analysis #46

**Comment by hwndept** [comment]
Sure, I want to switch to eslint. Another big reason is that JSCS has merged with ESLint and JSCS is deprecated.

**Comment by Fleischers** [comment]
Eslint also has rules on checking jsdocs #36 

http://eslint.org/docs/rules/valid-jsdoc
http://eslint.org/docs/rules/require-jsdoc

**Comment by hwndept** [comment]
That feature will be implemented as a part of #48
